# ~/.config/starship.toml
# Inspiration from https://github.com/ChristianLempa/dotfiles/blob/main/.config/starship.toml


# General stuff
add_newline = false
command_timeout = 1000


# The collected functions formatted
format = '''
\[$directory$git_branch$git_status\][\$](bold green) '''
right_format = '''
$os'''

[directory]
truncation_length = 3 # how long we gonna show
truncate_to_repo = true # when in git repo, won't show directories below the repo
use_os_path_sep = true # eg. \ on Windows instead of /
read_only_style = "197" # 8-bit ANSI
read_only = " (read-only)"
format = "[$path](bold green)[$read_only]($read_only_style)" # [~/Documents/Projects/whatever (read-only)]

[git_branch]
truncation_length = 5
style = "bold red"
format =  " [$branch]($style)"
disabled = false

[git_status]
conflicted = ""
ahead = ""
behind = ""
diverged = ""
up_to_date = ""
untracked = ""
stashed = ""
modified = '*'
staged = ""
renamed = ""
deleted = ""

style = "bold red"
format = "[$all_status]($style)"
disabled = false

[os]
format = "[$symbol]($style)"
style = "bold green"
disabled = false

[os.symbols]
Alpine = ""
Android = ""
Arch = "󰣇"
Artix = ""
CentOS = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Gentoo = "󰣨"
Linux = ""
Macos = ""
Manjaro = ""
Mint = "󰣭"
NixOS = ""
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = ""
Solus = ""
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""
