# ~/.config/starship.toml
# Inspiration from https://github.com/ChristianLempa/dotfiles/blob/main/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# General stuff
add_newline = false
command_timeout = 1000


# The collected functions formatted
format = '''
$hostname\[$directory$git_branch$git_status\][\$](bold green) ''' # [dir (git branch(git status))]$ 


[hostname]
ssh_only = false
trim_at = "."
style = "bold green"
format = "[$hostname]($style)"
disabled = false

[directory]
truncation_length = 3 # how long we gon show
truncate_to_repo = false # when in git repo, won't show directories below the repo
use_os_path_sep = true # eg. \ on Windows instead of /
read_only_style = "197" # 8-bit ANSI
read_only = " (read-only)"
format = "[$path](bold green)[$read_only]($read_only_style)" # [~/Documents/Projects/whatever (read-only)]
disabled = false

[git_branch]
truncation_length = 10
style = "bold red"
format =  " [$branch]($style)"
disabled = false

[git_status]
conflicted = ""
ahead = ""
behind = "!"
diverged = ""
up_to_date = ""
untracked = ""
stashed = ""
modified = "*"
staged = ""
renamed = ""
deleted = ""

style = "bold red"
format = "[$all_status]($style)"
disabled = false
